name: Deploy Houseiana Backend to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: houseiana-backend
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint --if-present

    - name: Run tests
      run: npm test --if-present

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build --if-present

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Create deployment package
      run: |
        # Remove dev dependencies and unnecessary files
        rm -rf node_modules
        npm ci --production

        # Create package excluding unnecessary files
        tar -czf deployment.tar.gz \
          --exclude='.git*' \
          --exclude='node_modules/.cache' \
          --exclude='*.log' \
          --exclude='test/' \
          --exclude='tests/' \
          --exclude='*.test.js' \
          --exclude='*.spec.js' \
          .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.tar.gz

    - name: Run database migrations
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          # Enable SSH and run migrations
          az webapp ssh --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group houseiana-rg --command "cd /home/site/wwwroot && npm run migrate:deploy"

  health-check:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Wait for deployment
      run: sleep 60

    - name: Health check
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health)
        if [ $response -eq 200 ]; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed with status: $response"
          exit 1
        fi

    - name: API endpoint test
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api)
        if [ $response -eq 200 ] || [ $response -eq 404 ]; then
          echo "✅ API endpoint accessible"
        else
          echo "❌ API endpoint test failed with status: $response"
          exit 1
        fi

    - name: Notify deployment success
      if: success()
      run: |
        echo "🚀 Deployment successful!"
        echo "🌐 App URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "📚 API Docs: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api"